spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examdb?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: My20001213
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /exam